Heredoc
ddiniz-m/minishell pull request #65
Opened 2023-10-20 17:40 UTC by ddiniz-m

This branch is called heredoc, but no heredoc was worked on.

Instead I handled environment variables and echo.

The way I did it is substitute the strings in the main for the respective env variables. Handling quotes, $ and other annoying cases.

2023-10-21 13:16 UTC, WudDoo commented
Our minishell doesn't interpret `echo "'$HOME'$PATH"` correctly
![image](https://github.com/ddiniz-m/minishell/assets/89762267/83ec56f9-814d-49d4-a53f-8bc08fb0baa0)
![image](https://github.com/ddiniz-m/minishell/assets/89762267/5846fd6e-63d3-4817-9a4f-45947f2685b0)

2023-10-21 13:26 UTC, WudDoo commented
It also doesn't handle `echo $HOME_m` correctly
![image](https://github.com/ddiniz-m/minishell/assets/89762267/ae311660-bb1b-428f-bc3f-0a078465ff2d)
![image](https://github.com/ddiniz-m/minishell/assets/89762267/2cf227ba-3fc3-40d9-9f06-d224793b5f26)

2023-10-21 13:28 UTC, WudDoo commented
`echo $HOME1` is also incorrect
![image](https://github.com/ddiniz-m/minishell/assets/89762267/9a195d6b-e05d-42a8-aa5c-295513ae4e7b)
![image](https://github.com/ddiniz-m/minishell/assets/89762267/324c717a-f27d-4ebb-b305-8f5033452797)

2023-10-21 13:31 UTC, WudDoo commented
Notes:
- `_` can be part of an environment value
- numbers can be part of an environment value
- single-quotes should be printed when inside double-quotes

2023-10-21 13:53 UTC, WudDoo commented
Our minishell SEGV's on `echo "$HOME'a"`
![image](https://github.com/ddiniz-m/minishell/assets/89762267/9b55fb62-3612-45a5-aa64-b4d2cf6eac71)
![image](https://github.com/ddiniz-m/minishell/assets/89762267/d0b71e14-b7b7-4eea-839f-b256b42035c4)

2023-10-22 17:08 UTC, WudDoo commented
Right now fails the following situations:
- `$VAR"a"`
- `"'$VAR'"`
- `"$VAR'a"`
- `$"VAR"`
- `$'VAR'`

We should keep testing to make sure its working in all cases. I added a text file with the cases I've been testing for.

2023-10-22 17:09 UTC, WudDoo commented
We should probably make a separate folder for the replacer

2023-10-27 10:50 UTC, ddiniz-m commented
Had errors. Will make a new one

2023-10-27 18:54 UTC, WudDoo commented
I think all the syntax error functions are fixed now. We should test tomorrow though.

2023-10-30 14:34 UTC, WudDoo requested changes

2023-10-30 14:34 UTC, WudDoo commented on src/built-ins/cd.c
cd shouldn't exit

2023-10-30 14:34 UTC, WudDoo commented on src/run/redirections.c
should actually create an open error function

2023-10-30 14:34 UTC, WudDoo commented on src/signals.c
should it write exit?

2023-10-30 16:10 UTC, WudDoo approved these changes

2023-10-30 16:12 UTC, merged